# Generated by Django 3.2.5 on 2021-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
